import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Card from "../components/Card"
import Topnavbar from '../components/Topnavbar'
import Image from 'next/image'

export default () => {
    return <div className={styles.container}>
        <Head>
            <title>Contact Us</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        </Head>

        <main className={styles.main} id='bg'>
            <Topnavbar index1={4} />
            <Card style={styles.contactcard}>
                <span className='s1 center'>
                    REACH US AT
                </span>
                <span className='s2'>
                    <span className='s1'>support@kicksup.com</span>
                    <span className='s3'>for any technical support</span>
                </span>
                <span className='s2'>
                    <span className='s1'>info@kicksup.com</span>
                    <span className='s3'>for more information</span>
                </span>
                <span className='s2'>
                    <span className='s1'>feedback@kicksup.com</span>
                    <span className='s3'>to send your feedback</span>
                </span>
                <span className='s2'>
                    <span className='s1'>jobs@kicksup.com</span>
                    <span className='s3'>to work with us</span>
                </span>
            </Card>
            <div className={styles.links}>
                <a href='#'>
                    <Image
                        src="/assets/twitter.png"
                        alt="websitelogo"
                        width={30}
                        height={30}
                    />
                </a>
                <a href='#'>
                    <Image
                        src="/assets/insta.png"
                        alt="websitelogo"
                        width={30}
                        height={30}
                    />
                </a>
                <a href='#'>
                    <Image
                        src="/assets/facebook.png"
                        alt="websitelogo"
                        width={30}
                        height={30}
                    />
                </a>



            </div>
        </main>

    </div>
}