import Head from 'next/head'
import Topnavbar from '../components/Topnavbar'
import styles from '../styles/Store.module.css'
import Left from '../components/Left'
import Middle from '../components/Middle'
import Right from '../components/Right'

export default () => {
    return (
        <div className={'container'}>
            <Head>
                <title>Store</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
            </Head>

            <main className={'main'}>
                <Topnavbar index1={3} />
                <div className={styles.box}>
                    <Left />
                    <Middle />
                    <Right />
                </div>
            </main>

        </div>
    )
}
