import Head from 'next/head'
import Topnavbar from '../components/Topnavbar'
import styles from '../styles/Home.module.css'

export default () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Team</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
            </Head>

            <main className={styles.main}>
                <Topnavbar index1={2} />
            </main>

        </div>
    )
}
